### ISSUE TITLE
Using User Hook

### ISSUE THREAD

**Issue by bryannbarbosa** [juampi92/adonis-mongoose-model#16]
How can I use this hook in my model? this is my config:

```
// Hooks/UserHook.js

const Hash = use('Hash')

const UserHook = exports = module.exports = {}

UserHook.hashPassword = async (user) => {
  user.password = await Hash.make(user.password)
}
```

```
// Models/User.js

const BaseModel = use('Model')
const mongooseHidden = require('mongoose-hidden', )({ defaultHidden: { password: true }})

/**
 * @class User
 */
class User extends BaseModel {
  static boot ({ schema }) {
    schema.plugin(mongooseHidden)
    this.addHook('beforeCreate', 'UserHook.hashPassword')
  }
  /**
   * User's schema
   */
  static get schema () {
    return {
      name: { type: String, required: true },
      email: { type: String, required: true },
      password: { type: String, required: true },
      type: { type:String, enum: ['root', 'dealer'], required: true },
      address: { type:String, required: true }
    }
  }

  static get primaryKey () {
    return '_id'
  }
}

module.exports = User.buildModel('User')
```

with this my configuration, returns this error, how can I solve it?

```
TypeError: this._schema[instruction] is not a function
TypeError: this._schema[instruction] is not a function
    at Function.addHook (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\adonis-mongoose-model\src\Model\Base.js:44:30)
    at Function.boot (C:\Users\Bryann\Desktop\works\formacho\android_app\server\app\Models\User.js:12:10)
    at Function.buildModel (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\adonis-mongoose-model\src\Model\Base.js:162:10)
    at Object.<anonymous> (C:\Users\Bryann\Desktop\works\formacho\android_app\server\app\Models\User.js:36:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at requireStack (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\require-stack\src\index.js:44:12)
    at Ioc._resolveAutoloadedPath (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\@adonisjs\fold\src\Ioc\index.js:265:20)
    at Ioc.make (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\@adonisjs\fold\src\Ioc\index.js:793:40)
    at MongooseSerializer.setConfig (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\adonis-mongoose-model\src\Serializers\MongooseSerializer.js:42:23)
    at Auth.authenticator (C:\Users\Bryann\Desktop\works\formacho\android_app\server\node_modules\@adonisjs\auth\src\Auth\index.js:113:24)
```

**Comment by bryannbarbosa** [comment]
I found the solution:

Instead of 'beforeCreate', i'm using 'preSave'

this.addHook('preSave', 'UserHook.hashPassword')

**Comment by juampi92** [comment]
Maybe I could improve this error, instead of showing `TypeError: this._schema[instruction] is not a function`, I could assert it first...

**Comment by mcordoba** [comment]
Same problem here... I need to generate a sequence before create only when creating

**Comment by bryannbarbosa** [comment]
Try deleting the `Hooks/User.js` file and use the following command to generate a new hook:
`adonis make: hook User`

Right after this, try using the following code as test:

```
'use strict'

const Hash = use ('Hash')

const UserHook = exports = module.exports = {}

UserHook.hashPassword = async (user) => {
   user.password = await Hash.make (user.password)
}
```

I had to delete the original Hook and recreate it to work.

Then add the following line to enable the hook: `this.addHook('preSave', 'UserHook.hashPassword')`

```
'use strict'

const BaseModel = use('Model')

/**
 * @class User
 */
class User extends BaseModel {
  static boot ({ schema }) {
    this.addHook('preSave', 'UserHook.hashPassword')
  }
  /**
   * User's schema
   */
  static get schema () {
    return {
      // your schema
    }
  }
  static get primaryKey () {
    return '_id'
  }
}

module.exports = User.buildModel('User')
```

This should work.

@mcordoba @juampi92

**Comment by mcordoba** [comment]
I was using beforeCreate instead of preSave as adonisjs say but I figured out that I should use the preSave in mongoose. Thank you

**Comment by juampi92** [comment]
On 3.0.0 I've added a more clear way of using middleware.

It tries to find a Lucid equivalent and if not, it throws an error so you know.

https://github.com/juampi92/adonis-mongoose-model/releases/tag/3.0.0
